language: node_js
dist: trusty
node_js: 8.9
sudo: true

addons:
  firefox: latest
  google-chrome: latest

before_install:
  - yarn global add greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update

script:
  # xvfb-run is needed for headless testing with Chrome and Firefox
  - xvfb-run yarn test

after_script:
  # repeat unit tests against dist/sweetalert2.all.min.js
  - sed -i 's/sweetalert2.js/sweetalert2.all.min.js/g' testem.json
  - xvfb-run yarn run check:tests
  - greenkeeper-lockfile-upload

notifications:
  email:
    on_success: never
